UniversityLibrarySystem/src/UniversityLibrarySystem.WEB/Controllers/Authors/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using UniversityLibrarySystem.DataAccess.Interfaces.Common;
using UniversityLibrarySystem.Domain.Entites;
using UniversityLibrarySystem.Service.Dtos;

namespace UniversityLibrarySystem.WEB.Controllers.Authors;

public class AuthorController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public AuthorController(IUnitOfWork unitOfWork)
    {
        this._unitOfWork = unitOfWork; 
    }
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet("createAuthor")]
    public ViewResult Create()
    {
        return View("Create");
    }

    [HttpPost("createAuthor")]
    [Route("Author/Create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateAuthorAsync(Author author)
    {
        if (ModelState.IsValid)
        {
            int res = _unitOfWork.AuthorRepository.Create(author);
            await _unitOfWork.SaveAsync();
            return Create();
        }
        return Create();
    }
}

UniversityLibrarySystem/src/UniversityLibrarySystem.WEB/Controllers/Books/BookController.cs
using Microsoft.AspNetCore.Mvc;
using UniversityLibrarySystem.DataAccess.Interfaces.Common;
using UniversityLibrarySystem.Service.Dtos;
using UniversityLibrarySystem.Service.Interfaces;

namespace UniversityLibrarySystem.WEB.Controllers.Books;

public class BookController : Controller
{
    private readonly IBookService _bookService;
    private readonly IUnitOfWork _unitOfWork;

    public BookController(IBookService bookService, IUnitOfWork unitOfWork)
    {
        this._bookService = bookService;
        this._unitOfWork = unitOfWork;
    }
    public IActionResult Index()
    {
        return View();
    }

    /// <summary>
    /// Displays the view for creating a new book.
    /// </summary>
    /// <returns>The view for creating a new student.</returns>

    [HttpGet("createBook")]
    public async Task<ViewResult> Create()
    {
        var genresList = await _unitOfWork.GenreRepository.GetAllAsync();
        var publishersList = await _unitOfWork.PublisherRepository.GetAllAsync();
        var authorsList = await _unitOfWork.AuthorRepository.GetAllAsync();
        ViewBag.genresList = genresList;
        ViewBag.publishersList = publishersList;
        ViewBag.authorsList = authorsList;
        return View("Create");
    }

    /// <summary>
    /// Handles the submission of a new book creation form.
    /// </summary>
    /// <param name="studentCreateDto">The data for creating a new book.</param>
    /// <returns>A redirect to the book index page if successful, otherwise the create view.</returns>
    [HttpPost("createBook")]
    [Route("Book/Create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateBookAsync(BookCreateDto bookCreateDto)
    {
        if (ModelState.IsValid)
        {
            await _bookService.CreateBookAsync(bookCreateDto);
            return await Create();
        }
        return await Create();
    }
}

UniversityLibrarySystem/src/UniversityLibrarySystem.WEB/Controllers/Publishers/PublisherController.cs
using Microsoft.AspNetCore.Mvc;
using UniversityLibrarySystem.DataAccess.Interfaces.Common;
using UniversityLibrarySystem.Domain.Entites;

namespace UniversityLibrarySystem.WEB.Controllers.Publishers;

public class PublisherController : Controller
{
    private IUnitOfWork _unitOfWork;

    public PublisherController(IUnitOfWork unitOfWork)
    {
        this._unitOfWork = unitOfWork;    
    }
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet("createPublisher")]
    public ViewResult Create()
    {
        return View("Create");
    }

    [HttpPost("createPublisher")]
    [Route("Publisher/Create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreatePublisherAsync(Publisher publisher)
    {
        if (ModelState.IsValid)
        {
            int res = _unitOfWork.PublisherRepository.Create(publisher);
            await _unitOfWork.SaveAsync();
            return Create();
        }
        return Create();
    }
}

UniversityLibrarySystem/src/UniversityLibrarySystem.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniversityLibrarySystem.WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UniversityLibrarySystem.WEB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UniversityLibrarySystem.WEB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Create">Create book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Create">Create author</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publisher" asp-action="Create">Create publisher</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Create">Register student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students list</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - UniversityLibrarySystem.WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>